name: Android CI

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: 'debug or release'
        required: false
        default: 'debug'
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses
        run: yes | sdkmanager --licenses

      - name: Install SDKMAN and Gradle 8.9
        shell: bash
        run: |
          curl -s https://get.sdkman.io | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.9
          gradle --version

      - name: Build (debug or release) with Gradle
        shell: bash
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          if [ "${{ github.event.inputs.build-type }}" = "release" ]; then
            gradle :app:bundleRelease :app:assembleRelease
          else
            gradle :app:assembleDebug
          fi
        env:
          RELEASE_STORE_FILE: ${{ secrets.RELEASE_STORE_FILE }}
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

      - name: Upload Debug APK
        if: ${{ github.event.inputs.build-type != 'release' }}
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload Release APK
        if: ${{ github.event.inputs.build-type == 'release' }}
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Upload Release AAB
        if: ${{ github.event.inputs.build-type == 'release' }}
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: app/build/outputs/bundle/release/app-release.aab
